# Generated by Django 5.2.8 on 2025-11-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_abdominal_pain_medicalrecord_abdominal_pain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
    ]
